import React from 'react'
import { useNavigate } from 'react-router'

function Home() {

  const navigate = useNavigate();
  return (
    <div>
      {/* Hero Section */}
      This has been generated by ai for now, will be styled later
      <section style={{ padding: '50px', textAlign: 'center', backgroundColor: '#f4f4f4' }}>
        <h1>Welcome to Expense Tracker</h1>
        <p>Track your expenses and manage your finances effortlessly.</p>
        <button className='rounded-2xl p-3 m-2 cursor-pointer bg-amber-500 hover:bg-amber-100 duration-200 ease-in-out' onClick={() => navigate("/app")}>Get Started</button>
      </section>

      {/* Features Section */}
      <section style={{ padding: '50px', textAlign: 'center' }}>
        <h2>Why Choose Expense Tracker?</h2>
        <div style={{ display: 'flex', justifyContent: 'space-around', marginTop: '30px' }}>
          <div style={{ maxWidth: '300px' }}>
            <h3>Easy to Use</h3>
            <p>Our intuitive interface makes tracking expenses a breeze.</p>
          </div>
          <div style={{ maxWidth: '300px' }}>
            <h3>Detailed Reports</h3>
            <p>Get insights into your spending habits with detailed reports.</p>
          </div>
          <div style={{ maxWidth: '300px' }}>
            <h3>Secure</h3>
            <p>Your data is safe with our top-notch security measures.</p>
          </div>
        </div>
      </section>

      {/* Call to Action Section */}
      <section style={{ padding: '50px', textAlign: 'center', backgroundColor: '#f4f4f4' }}>
        <h2>Start Managing Your Expenses Today</h2>
        <button style={{ padding: '10px 20px', fontSize: '16px', cursor: 'pointer' }}>Sign Up Now</button>
      </section>
    </div>
  )
}

export default Home